### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by dejan-cti** [svg-sprite/grunt-svg-sprite#115]
Hello! I was hoping to use this plugin as a replacement for `grunticon`, which has been deprecated. The syntax for making a grunt task looks almost the same, so it's a good fit. Unfortunately, it doesn't seem to be working for me. I've tried debugging it and everything looked correct until the `spriter.compile()` part in the `grunt-svg-sprite/svg_sprite.js` file. It seems that the `result` variable is empty, even though the `spriter` variable isn't. Do you have any suggestions about this issue? I've used the example config code from your readme file, so the setup is pretty basic.

**Comment by dejan-cti** [comment]
It actually works, I forgot to include the options parameter...

**Comment by huda-kh** [comment]
> It actually works, I forgot to include the options parameter...
Can you expand on that? I'm having the same issue, was hoping to use it in place of  `grunticon` but there is no output.

**Comment by dejan-cti** [comment]
@huda-kh try to include some options as described in the plugin example.
