### ISSUE TITLE
Tests fail on macOS Sierra

### ISSUE THREAD

**Issue by philchanet** [svg-sprite/grunt-svg-sprite#79]
Thanks for this great tool - the test phase fails and returns the following errors. I'm not sure if I'm missing a grunt option (I simply use `grunt` to launch it)?

```
Running "nodeunit:tests" (nodeunit) task
Testing svg_sprite_test.jsFatal error: write EPIPE
Error: write EPIPE
  at exports._errnoException (util.js:1036:11)
  at WriteWrap.afterWrite (net.js:794:14)
```

**Comment by jkphl** [comment]
@philchanet Thanks for reporting. Unfortunately, I don't have a MacOS Sierra handy (in fact, I don't have a Mac handy at all), so I don't see a way to dig into this at the moment. Anyone else?

**Comment by XhmikosR** [comment]
Seems to work now on macOS-latest on [CI](https://github.com/svg-sprite/grunt-svg-sprite/actions/runs/2046941120).
